# Disciplina: Introdução a Ciências de Dados
## Aula: Jupyter e Google Colab

In [ ]:
# Demonstração das IDEs

# Aula: Biblioteca NUMPY

### Numpy = Numerical Python -> pacote mais importante para processamento numérico;
### Muito utilizado para array (listas) e também para array multidimensional com operações aritiméticas rápidas
### estatísticas descritivas, agregação e sintetização de dados; expressões lógicas condicionais na forma de expressão ao invés de usar laços com desvios (if, else…); fundamental compreender isso para ser um ótimo profissional de DS.
### além disso a diferença de performance é brutal (10 a 100x mais rápido); manipulação de dados em grupos (agregação, transformação e aplicação de funções).

# Importar Biblioteca

In [1]:
import numpy as np

# Gerar Dados Aleatórios

### Gerar um NDArray de 2x3 (duas listas com três elementos)

In [2]:
dados = np.random.rand(2, 3)

In [4]:
dados

array([[0.44167868, 0.10815989, 0.12563966],
       [0.31864052, 0.74987799, 0.87659007]])

### Tipo do Array

In [5]:
dados.dtype

dtype('float64')

### Tamanho e quantidade de dimensões


In [6]:
dados.shape

(2, 3)

In [7]:
dados.ndim

2

### Criar ndarray usando a função array

Ao criar o array a função arra tenta urilizar o melhor tipo de dado

In [8]:
lista = [1, 2, 5, 7.8, 1.25]

In [9]:
dados2 = np.array(lista)

In [10]:
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [11]:
lista2 = [[1, 2, 3, 4], [4,3,2,1]]

In [12]:
dados3 = np.array(lista2)

In [13]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

### Outras maneiras de criar arrays

In [14]:
dadoszero = np.zeros(10)

In [15]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
dadoszero2 = np.zeros((2,3))

In [17]:
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
dadosum = np.ones(5)

In [19]:
dadosum

array([1., 1., 1., 1., 1.])

In [21]:
dadosseq = np.arange(10)

In [22]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
dadosseq2 = np.arange(0, 20, 2)

In [24]:
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
dadosseq.dtype

dtype('int64')

In [26]:
#tranformar array
dadosseqfloat = dadosseq.astype(np.float64)

In [27]:
dadosseqfloat

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Aritméticas com Arrays

In [28]:
dados4 = np.array([[1, 2, 3], [4, 5, 6]])

In [29]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
dados4 * dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
dados4 - dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [33]:
dados5 = dados4 + dados4

In [34]:
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [35]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
dados5 > dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

# Indexação

In [37]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
dadosseq[5]

np.int64(5)

In [40]:
dadosseq[6]

np.int64(6)

### Diferente de uma lista python, um recorte (fatia) de um ndarray sofrerá broadcast - é como se fosse uma view de bando de dados.
### Com conjuntos imensos de dados isso é uma grande vantagem em relação a performance

In [44]:
dadosseq[3:6] #posição 6 não entra

array([20, 20, 20])

In [45]:
dadosseq[3:6] = 20

In [46]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [47]:
fatiadados=dadosseq[2:4]

In [48]:
fatiadados

array([ 2, 20])

In [49]:
fatiadados[1] = 2000

In [50]:
fatiadados

array([   2, 2000])

In [51]:
dadosseq #Como fiz copia (fatiadados=dadosseq[2:4]) ele vai remeter no valor original  ------> broadcast

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [54]:
fatiadados[:] = 333 # [:] -----> pego todos os valores no caso de fatiadados do 2 até o 4, dois valores

In [55]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

### Copiar dados

In [56]:
fatia2 = dadosseq[2:4].copy() #assim faço apenas uma cópia e nbão mudo a estrutura inicial/original

In [57]:
fatia2

array([333, 333])

In [58]:
fatia2[:]=111

In [59]:
fatia2

array([111, 111])

In [60]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

### Array com mais de uma dimensão

In [61]:
dados6 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [62]:
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
dados6[1,2] # resultado é 6, pq as linhas são 0,1,2 e os dados 0,1,2 em cada linha, lembrar que inicia em 0

np.int64(6)

# Máscaras

In [64]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [65]:
mascara = (dadosseq<100) # Máscara = comparação --------> gera um array com a comparação

In [66]:
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [67]:
dadosseq[dadosseq<20] = 8888

In [68]:
dadosseq

array([8888, 8888,  333,  333,   20,   20, 8888, 8888, 8888, 8888])

# Transposição

In [69]:
dados7 = np.arange(15).reshape((3,5))

In [70]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
dados7.T # T = transposição, inverte a forma do array se é 3 linhas com 5 dados, vai ser 5 linhas com 3 dados

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Multiplicação de Matrizes

In [73]:
np.dot(dados7.T, dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

# Vejam que há muitas outras funções que podem ser exploradas como: sin, cos, power, mod, sqrt entre outros
